public class Questao001 {

    public static void main(String[] args) {
        

                int [] vetA = new int[num];



            for (int i = 0; i > num; i++){


               vetA[i] = JOptionPane.showInputDialog(null, "Entre com o "+(i+1)+"° número.")


            }
            
            for (int i = 0; i < num; i++){


                if (vetA[i]<0){


                    JOptionPane.showMessageDialog(null, "O número "+vetA[i]+" na posição "+(i+1)+" é negativo.")


                }



              }
             }
            }
